# profile.yaml — SPEED-TUNED
meta:
  audience: "Senior executives in technology strategy, investment governance, finance & operations (Banking/FS)"
  org_priorities:
    - Operational Efficiency
    - Risk & Compliance
    - AI & Automation
    - Cloud & Data Platform
  coverage_days: 30
  timezone: "Asia/Singapore"

scoring:
  keywords:
    regulation: 1.2
    compliance: 1.2
    aml: 1.2
    kyc: 1.2
    sanctions: 1.2
    resilience: 1.1
    outage: 1.3
    incident: 1.2
    vulnerability: 1.3
    breach: 1.3
    ransomware: 1.3
    ai: 1.1
    genai: 1.2
    automation: 1.1
    cloud: 1.1
    data: 1.1
    payments: 1.1
    iso20022: 1.2
    swift: 1.1
    capital: 1.2
    liquidity: 1.1
    risk: 1.2
  base_source_weight:
    regulators: 1.5
    vendors: 1.2
    analyst_firms: 1.0
    consulting: 0.9
    communities: 0.7
