# Curate sources by category. You can add more entries safely.
# type: rss | page (rss is easiest/most reliable)
analyst_firms:
  - name: IDC Blogs
    type: rss
    url: https://blogs.idc.com/feed/
    weight: 1.0
  - name: Forrester (podcasts & posts)
    type: rss
    url: https://www.forrester.com/blogs/feed/
    weight: 0.8
  # Gartner is largely gated; use newsletters or manual review.
  # - name: Gartner (manual)
  #   type: page
  #   url: https://www.gartner.com/en/newsroom/press-releases
  #   weight: 0.6

consulting:
  - name: McKinsey Podcast
    type: rss
    url: https://www.mckinsey.com/featured-insights/mckinsey-podcast/rss
    weight: 0.8
  - name: BCG Podcasts (The So What)
    type: rss
    url: https://feeds.simplecast.com/2h0Wz2cc
    weight: 0.7
  - name: Bain Audio (Customer Confidential)
    type: rss
    url: https://www.bain.com/bainweb/media/podcast/loyalty-podcast.xml
    weight: 0.6
  - name: Deloitte IAS Plus (has RSS)
    type: rss
    url: https://www.iasplus.com/en/rss
    weight: 0.7

regulators:
  - name: BIS – Press releases
    type: rss
    url: https://www.bis.org/rss/press_releases.xml
    weight: 1.0
  - name: FCA – News
    type: rss
    url: https://www.fca.org.uk/news/rss.xml
    weight: 1.0
  # MAS offers email alerts; no official RSS listed. You can add web pages with 'page' type for manual checks.
  # - name: MAS – Newsroom (manual/email)
  #   type: page
  #   url: https://www.mas.gov.sg/news
  #   weight: 1.0

vendors:
  - name: AWS – What's New
    type: rss
    url: https://aws.amazon.com/about-aws/whats-new/recent/feed/
    weight: 1.0
  - name: Azure – Updates
    type: rss
    url: https://azure.microsoft.com/updates/feed/
    weight: 1.0
  - name: SAP News Center (EN)
    type: rss
    url: https://news.sap.com/feed/en/
    weight: 0.8
  # ServiceNow's corporate blog doesn't publish a universal RSS; consider press room email alerts.

communities:
  - name: BIAN – Newsroom (no RSS, page only)
    type: page
    url: https://bian.org/news-room/
    weight: 0.6
  - name: SWIFT – News
    type: page
    url: https://www.swift.com/news-events/news
    weight: 0.8
  - name: ISG – Research Insights
    type: page
    url: https://isg-one.com/articles
    weight: 0.6
