name: Build Monthly Intelligence Brief
run-name: "Monthly Intelligence Brief — #${{ github.run_number }} by ${{ github.triggering_actor }}"

on:
  schedule:
    # 02:00 UTC on the 15th (10:00 SGT). Change if you like.
    - cron: '0 2 15 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Show versions (debug)
        run: |
          python -V
          pip -V

      - name: Install dependencies
        continue-on-error: true
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare output dir
        run: mkdir -p output

      - name: Run generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        continue-on-error: true
        run: |
          python main.py || true

      # ALWAYS runs; if no HTML exists, write a tiny fallback so upload succeeds.
      - name: Ensure artifact exists (fallback if needed)
        if: always()
        run: |
          if ! ls output/*.html >/dev/null 2>&1; then
            python - <<'PY'
from datetime import datetime
import os
os.makedirs('output', exist_ok=True)
d = datetime.utcnow().strftime('%Y-%m-%d')
html = f"""<!doctype html><meta charset="utf-8">
<title>Monthly Intelligence Brief — {d}</title>
<body style='font-family:system-ui;margin:40px'>
<h1>Monthly Intelligence Brief — {d}</h1>
<p>Fallback brief generated by CI so the artifact is always available.
Open this run’s logs for the exact error & fix.</p>
</body>"""
open(f"output/monthly_intel_{d}.html","w",encoding="utf-8").write(html)
print("Created fallback HTML")
PY
          fi

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: monthly-brief
          path: output/*.html
          if-no-files-found: warn
