name: Build Monthly Intelligence Brief

on:
  schedule:
    # 02:00 UTC on the 15th of each month (10:00 SGT)
    - cron:  '0 2 15 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: monthly-intel
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare output dir
        run: mkdir -p output

      - name: Generate brief (with fallback)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          set -eo pipefail
          echo "Running main.py…"
          if ! python main.py ; then
            echo "::warning::main.py failed. Creating fallback HTML."
          fi
          # If no HTML exists, create a minimal fallback so upload never fails
          if ! ls output/*.html >/dev/null 2>&1; then
            python - <<'PY'
from datetime import datetime
import os
os.makedirs('output', exist_ok=True)
d = datetime.utcnow().strftime('%Y-%m-%d')
html = f"""<!doctype html><meta charset="utf-8"><title>Monthly Intelligence Brief — {d}</title>
<body style='font-family:system-ui;margin:40px'>
<h1>Monthly Intelligence Brief — {d}</h1>
<p>Fallback brief created by CI so the artifact is always available.</p>
</body>"""
open(f"output/monthly_intel_{d}.html","w",encoding="utf-8").write(html)
print("Wrote fallback brief to output/")
PY
          fi
          echo "Done."

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: monthly-brief
          path: output/*.html
          if-no-files-found: warn

