name: Build Monthly Intelligence Brief
run-name: "Monthly Intelligence Brief — #${{ github.run_number }} by ${{ github.triggering_actor }}"
on:
  schedule:
    # 02:00 UTC on the 15th of each month (10:00 SGT)
    - cron:  '0 2 15 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: monthly-intel
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare output dir
        run: mkdir -p output

      # This step NEVER fails the job. If main.py fails or writes no HTML,
      # we generate a minimal fallback HTML so the artifact always exists.
      - name: Generate brief (with fallback)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python - <<'PY'
import os, sys, glob, subprocess, datetime
os.makedirs('output', exist_ok=True)
rc = subprocess.call([sys.executable, 'main.py'])
if rc != 0 or not glob.glob('output/*.html'):
    d = datetime.datetime.utcnow().strftime('%Y-%m-%d')
    html = f"""<!doctype html><meta charset="utf-8">
<title>Monthly Intelligence Brief — {d}</title>
<body style='font-family:system-ui;margin:40px'>
<h1>Monthly Intelligence Brief — {d}</h1>
<p>Fallback brief generated by CI so the artifact is always available.
Check the workflow logs for the underlying error.</p>
</body>"""
    open(f"output/monthly_intel_{d}.html","w",encoding="utf-8").write(html)
    print("Created fallback HTML.")
sys.exit(0)  # never fail the job at this step
PY

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: monthly-brief
          path: output/*.html
          if-no-files-found: warn
