name: Build Monthly Intelligence Brief
run-name: "Monthly Intelligence Brief — #${{ github.run_number }}"

on:
  workflow_dispatch:    # enables the “Run workflow” button
  schedule:
    # 02:00 UTC on the 16th of every month (10:00 SGT) – change if you want
    - cron: '0 2 16 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare output dir
        run: mkdir -p output

      - name: Generate brief
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python main.py

      - name: Upload artifact (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: monthly-brief
          path: output/*.html
          if-no-files-found: warn
